### ISSUE TITLE
关于普通加法/减法/乘法的问题

### ISSUE THREAD

**Issue by TransparentLC** [Smallorange666/Large-Number-Operation#1]
不太确定这里为什么要全程使用 `uint32_t[]` 表示大整数，用 `uint64_t[]` 的话性能应该会更好一些？

gcc 和 clang 都可以用 `__int128_t` 和 `__uint128_t`（但是 MSVC 不行），这样普通乘法可以用两个 `uint64_t` 相乘得到 `__uint128_t` 再移位得到高 64 bit。加法的话，虽然也可以两个 `uint64_t` 相加得到 `__uint128_t` 再获取进位，不过其实也可以用 [Integer Overflow Builtins (Using the GNU Compiler Collection (GCC))](https://gcc.gnu.org/onlinedocs/gcc/Integer-Overflow-Builtins.html)，减法同理。

**Comment by Smallorange666** [comment]
感谢issue！

一开始有想过`uint64_t`的，但是看到128位的类型命名稍有不同，以为兼容性没那么好（完全是自以为的），就没有选用。

后面会尝试改为`uint64_t`，并且将一些magic number抽象为常量。

**Comment by Smallorange666** [comment]
`uint64_t[ ]`的版本在这个 a3d0f8da191bb92e902eb760c7ccdb5dd4c08f74 commit 中，并且做了相应的精简。同时，[博客](https://smallorange666.github.io/2024/11/29/%E5%A4%A7%E6%95%B0%E8%BF%90%E7%AE%97%E5%AE%9E%E7%8E%B0/)也进行了同步更新。
